### ISSUE TITLE
Release Pipeline Build Number

### ISSUE THREAD

**Issue by greenrya** [WaelHamze/dyn365-ce-vsts-tasks#143]
I have successfully created a build that takes a backup of a instance and am trying to use the Release pipeline for restore.  In my build pipeline I use the build number as the back-up label.  I am having a hard time getting this variable in the Release any tips on how I can best pass the label of the backup from the source instance to be used for restore into target instance in the Release pipeline?

2020-02-05T22:17:23.6940512Z ##[section]Starting: Restore 
2020-02-05T22:17:23.7109905Z ==============================================================================
2020-02-05T22:17:23.7109976Z Task         : MSCRM Restore Instance
2020-02-05T22:17:23.7110026Z Description  : Restores an online instance from a previous backup
2020-02-05T22:17:23.7110059Z Version      : 10.0.3
2020-02-05T22:17:23.7110095Z Author       : Wael Hamze
2020-02-05T22:17:23.7110126Z Help         : This task uses the Microsoft.Xrm.OnlineManagementAPI: https://www.powershellgallery.com/packages/Microsoft.Xrm.OnlineManagementAPI
2020-02-05T22:17:23.7110174Z ==============================================================================
2020-02-05T22:18:03.5646117Z ##[error]Backup with label $(RELEASE.ARTIFACTS.Build - Play365-CI-D365-CRM-Backup Development.BUILDNUMBER) not found
2020-02-05T22:18:03.6278565Z ##[section]Finishing: Restore

**Comment by greenrya** [comment]
I was able to resolve my issue through training and now have access to the Build Number variable and can pass it to the task:
2020-02-06T16:14:04.2328183Z ##[debug]BackupLabel = 2020.02.06.1

But now get this error:
**2020-02-06T16:14:59.7613261Z ##[debug]Caught exception from task script.
2020-02-06T16:14:59.7644140Z ##[debug]Error record:
2020-02-06T16:14:59.8298214Z ##[debug]D:\a\_tasks\MSCRMRestoreOnlineInstance_a6eb6b39-f378-4328-b533-d88f36be7a2a\10.0.3\MSCRMRestoreOnlineInstance.ps1 : Parameter set cannot be resolved using the specified named parameters.
2020-02-06T16:14:59.8309694Z ##[debug]At line:1 char:1
2020-02-06T16:14:59.8321823Z ##[debug]+ . 'd:\a\_tasks\MSCRMRestoreOnlineInstance_a6eb6b39-f378-4328-b533-d88 ...
2020-02-06T16:14:59.8333156Z ##[debug]+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-02-06T16:14:59.8344698Z ##[debug]    + CategoryInfo          : InvalidArgument: (:) [MSCRMRestoreOnlineInstance.ps1], ParameterBindingException
2020-02-06T16:14:59.8356466Z ##[debug]    + FullyQualifiedErrorId : AmbiguousParameterSet,MSCRMRestoreOnlineInstance.ps1
2020-02-06T16:14:59.8367757Z ##[debug] 
2020-02-06T16:14:59.8386660Z ##[debug]Script stack trace:
2020-02-06T16:14:59.8419584Z ##[debug]at <ScriptBlock>, D:\a\tools\MSCRMBuildTools\9.1.2\xRMCIFramework\9.0.0\RestoreOnlineInstance.ps1: line 77
2020-02-06T16:14:59.8431111Z ##[debug]at <ScriptBlock>, D:\a\_tasks\MSCRMRestoreOnlineInstance_a6eb6b39-f378-4328-b533-d88f36be7a2a\10.0.3\MSCRMRestoreOnlineInstance.ps1: line 38
2020-02-06T16:14:59.8442268Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-02-06T16:14:59.8453732Z ##[debug]at <ScriptBlock>, <No file>: line 22
2020-02-06T16:14:59.8465902Z ##[debug]at <ScriptBlock>, <No file>: line 18
2020-02-06T16:14:59.8477749Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-02-06T16:14:59.8495568Z ##[debug]Exception:
2020-02-06T16:14:59.8537519Z ##****[debug]System.Management.Automation.ParameterBindingException: Parameter set cannot be resolved using the specified named parameters.****
2020-02-06T16:14:59.8548991Z ##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2020-02-06T16:14:59.8560139Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2020-02-06T16:14:59.8571714Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2020-02-06T16:14:59.8582763Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2020-02-06T16:14:59.8594070Z ##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2020-02-06T16:14:59.8605193Z ##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2020-02-06T16:14:59.8617041Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
2020-02-06T16:14:59.8628065Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
2020-02-06T16:14:59.8640099Z ##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
2020-02-06T16:14:59.8948622Z ##[error]Parameter set cannot be resolved using the specified named parameters.
2020-02-06T16:14:59.8957361Z ##[debug]Processed: ##vso[task.logissue type=error]Parameter set cannot be resolved using the specified named parameters.
2020-02-06T16:14:59.8978411Z ##[debug]Processed: ##vso[task.complete result=Failed]
2020-02-06T16:14:59.9317017Z ##[section]Finishing: Restore 
**

**Comment by WaelHamze** [comment]
@greenrya glad you got this resolved.
