### ISSUE TITLE
Unable to Login to Dynamics CRM using Authtype=Office365

### ISSUE THREAD

**Issue by nishshade** [WaelHamze/dyn365-ce-vsts-tasks#152]
2020-02-21T13:03:02.8845257Z ##[debug]Evaluating condition for step: 'MSCRM CRM Ping copy'
2020-02-21T13:03:02.8846131Z ##[debug]Evaluating: succeeded()
2020-02-21T13:03:02.8846238Z ##[debug]Evaluating succeeded:
2020-02-21T13:03:02.8846567Z ##[debug]=> True
2020-02-21T13:03:02.8846776Z ##[debug]Result: True
2020-02-21T13:03:02.8846985Z ##[section]Starting: MSCRM CRM Ping copy
2020-02-21T13:03:02.9092366Z ==============================================================================
2020-02-21T13:03:02.9092419Z Task         : MSCRM Ping
2020-02-21T13:03:02.9092449Z Description  : A sample task that checks connectivity to a Dynamics 365 environment
2020-02-21T13:03:02.9092511Z Version      : 10.0.6
2020-02-21T13:03:02.9092540Z Author       : Wael Hamze
2020-02-21T13:03:02.9092568Z Help         : Performs a WhoAmIRequest against the target CRM environment
2020-02-21T13:03:02.9092596Z ==============================================================================
2020-02-21T13:03:03.7329079Z ##[debug]VstsTaskSdk 0.10.0 commit 787a46ec0a2df5b4d12c2e801bd3f319975c054c
2020-02-21T13:03:03.8394762Z ##[debug]Entering MSCRMPing.ps1
2020-02-21T13:03:03.8616256Z ##[debug]INPUT_CRMCONNECTIONSTRING: 'AuthType=Office365;Username=xxx;Password=xxx;Url=https://gsrci.crm11.dynamics.com'
2020-02-21T13:03:03.8644738Z ##[debug]crmConnectionString = AuthType=Office365;Username=xxx;Password=xxx;Url=https://gsrci.crm11.dynamics.com
2020-02-21T13:03:03.8753784Z ##[debug]Script Path: F:\BuildAgent_01\_work\_tasks\MSCRMPing_d8587a60-cd25-11e6-a324-f3fd298c325e\10.0.6
2020-02-21T13:03:03.8795870Z ##[debug]MSCRM Tools Path: F:\BuildAgent_01\_work\tools\MSCRMBuildTools\9.1.3
2020-02-21T13:03:03.9023230Z ##[debug]Entering Ping.ps1
2020-02-21T13:03:03.9092524Z ##[debug]CrmConnectionString = AuthType=Office365;Username=xxx;Password=xxx;Url=https://gsrci.crm11.dynamics.com
2020-02-21T13:03:03.9160807Z ##[debug]Script Path: F:\BuildAgent_01\_work\tools\MSCRMBuildTools\9.1.3\xRMCIFramework\9.0.0
2020-02-21T13:03:03.9187757Z ##[debug]Importing CIToolkit: F:\BuildAgent_01\_work\tools\MSCRMBuildTools\9.1.3\xRMCIFramework\9.0.0\Xrm.Framework.CI.PowerShell.Cmdlets.dll
2020-02-21T13:03:03.9218588Z ##[debug]Loading module from path 'F:\BuildAgent_01\_work\tools\MSCRMBuildTools\9.1.3\xRMCIFramework\9.0.0\Xrm.Framework.CI.PowerShell.Cmdlets.dll'.
2020-02-21T13:03:03.9316416Z ##[debug]Importing cmdlet 'Add-XrmEntity'.
2020-02-21T13:03:03.9351460Z ##[debug]Importing cmdlet 'Add-XrmLanguagePack'.
2020-02-21T13:03:03.9373419Z ##[debug]Importing cmdlet 'Add-XrmSolution'.
2020-02-21T13:03:03.9396520Z ##[debug]Importing cmdlet 'Add-XrmSolutionPatch'.
2020-02-21T13:03:03.9421369Z ##[debug]Importing cmdlet 'Compress-XrmCMData'.
2020-02-21T13:03:03.9447428Z ##[debug]Importing cmdlet 'Expand-XrmCMData'.
2020-02-21T13:03:03.9472822Z ##[debug]Importing cmdlet 'Expand-XrmSolution'.
2020-02-21T13:03:03.9498450Z ##[debug]Importing cmdlet 'Compress-XrmSolution'.
2020-02-21T13:03:03.9519363Z ##[debug]Importing cmdlet 'Get-XrmConnections'.
2020-02-21T13:03:03.9542462Z ##[debug]Importing cmdlet 'Set-XrmEnvironmentVariableValue'.
2020-02-21T13:03:03.9565369Z ##[debug]Importing cmdlet 'Get-XrmEnvironmentVariableValue'.
2020-02-21T13:03:03.9590751Z ##[debug]Importing cmdlet 'Get-XrmSolutionMissingDependencies'.
2020-02-21T13:03:03.9614972Z ##[debug]Importing cmdlet 'Get-XrmSolutionMissingComponents'.
2020-02-21T13:03:03.9638366Z ##[debug]Importing cmdlet 'Publish-XrmTheme'.
2020-02-21T13:03:03.9664007Z ##[debug]Importing cmdlet 'Remove-XrmConnection'.
2020-02-21T13:03:03.9686480Z ##[debug]Importing cmdlet 'Get-XrmConnection'.
2020-02-21T13:03:03.9712452Z ##[debug]Importing cmdlet 'Set-XrmConnection'.
2020-02-21T13:03:03.9739799Z ##[debug]Importing cmdlet 'Copy-XrmSolutionComponents'.
2020-02-21T13:03:03.9766805Z ##[debug]Importing cmdlet 'Export-XrmAccessTeamTemplates'.
2020-02-21T13:03:03.9791204Z ##[debug]Importing cmdlet 'Export-XrmSolutions'.
2020-02-21T13:03:03.9816080Z ##[debug]Importing cmdlet 'Export-XrmSolution'.
2020-02-21T13:03:04.0595089Z ##[debug]Importing cmdlet 'Get-XrmEntities'.
2020-02-21T13:03:04.0606393Z ##[debug]Importing cmdlet 'Get-XrmEntity'.
2020-02-21T13:03:04.0639150Z ##[debug]Importing cmdlet 'Get-XrmLanguagePacks'.
2020-02-21T13:03:04.0672620Z ##[debug]Importing cmdlet 'Get-XrmPluginRegistrationClass'.
2020-02-21T13:03:04.0711721Z ##[debug]Importing cmdlet 'Get-XrmPluginRegistrationFromAssembly'.
2020-02-21T13:03:04.0732972Z ##[debug]Importing cmdlet 'Get-XrmServiceEndpointRegistration'.
2020-02-21T13:03:04.0758302Z ##[debug]Importing cmdlet 'Get-XrmPluginRegistration'.
2020-02-21T13:03:04.0781231Z ##[debug]Importing cmdlet 'Get-XrmSolutionPatches'.
2020-02-21T13:03:04.0803924Z ##[debug]Importing cmdlet 'Get-XrmSolution'.
2020-02-21T13:03:04.0827925Z ##[debug]Importing cmdlet 'Get-XrmSolutionImportLog'.
2020-02-21T13:03:04.0854809Z ##[debug]Importing cmdlet 'Get-XrmSolutionInfoFromFolder'.
2020-02-21T13:03:04.0892880Z ##[debug]Importing cmdlet 'Get-XrmSolutionInfoFromZip'.
2020-02-21T13:03:04.0914884Z ##[debug]Importing cmdlet 'Import-XrmAccessTeamTemplates'.
2020-02-21T13:03:04.0938938Z ##[debug]Importing cmdlet 'Import-XrmSolutions'.
2020-02-21T13:03:04.0961157Z ##[debug]Importing cmdlet 'Merge-XrmSolution'.
2020-02-21T13:03:04.0984136Z ##[debug]Importing cmdlet 'Import-XrmSolution'.
2020-02-21T13:03:04.1010559Z ##[debug]Importing cmdlet 'Merge-XrmSolutionPatches'.
2020-02-21T13:03:04.1034898Z ##[debug]Importing cmdlet 'New-XrmBulkDeleteJob'.
2020-02-21T13:03:04.1056823Z ##[debug]Importing cmdlet 'New-XrmEntity'.
2020-02-21T13:03:04.1079405Z ##[debug]Importing cmdlet 'Publish-XrmCustomizations'.
2020-02-21T13:03:04.1103660Z ##[debug]Importing cmdlet 'Publish-XrmDuplicateRule'.
2020-02-21T13:03:04.1146934Z ##[debug]Importing cmdlet 'Remove-XrmEntityAttribute'.
2020-02-21T13:03:04.1175856Z ##[debug]Importing cmdlet 'Remove-XrmEntity'.
2020-02-21T13:03:04.1698659Z ##[debug]Importing cmdlet 'Remove-XrmOption'.
2020-02-21T13:03:04.1750863Z ##[debug]Importing cmdlet 'Remove-XrmWorkflow'.
2020-02-21T13:03:04.1773554Z ##[debug]Importing cmdlet 'Remove-XrmRecord'.
2020-02-21T13:03:04.1806022Z ##[debug]Importing cmdlet 'Set-XrmDashboardRole'.
2020-02-21T13:03:04.1827418Z ##[debug]Importing cmdlet 'Set-XrmEntityState'.
2020-02-21T13:03:04.1848497Z ##[debug]Importing cmdlet 'Set-XrmWorkflowState'.
2020-02-21T13:03:04.1869273Z ##[debug]Importing cmdlet 'Compress-XrmSolutions'.
2020-02-21T13:03:04.1888259Z ##[debug]Importing cmdlet 'Show-XrmLogging'.
2020-02-21T13:03:04.1911876Z ##[debug]Importing cmdlet 'Remove-XrmSolutionComponents'.
2020-02-21T13:03:04.1930044Z ##[debug]Importing cmdlet 'Select-WhoAmI'.
2020-02-21T13:03:04.1952764Z ##[debug]Importing cmdlet 'Remove-XrmPluginAssembly'.
2020-02-21T13:03:04.1973826Z ##[debug]Importing cmdlet 'Set-XrmServiceEndpointRegistration'.
2020-02-21T13:03:04.1995050Z ##[debug]Importing cmdlet 'Set-XrmWebResourcesFromFolder'.
2020-02-21T13:03:04.2015679Z ##[debug]Importing cmdlet 'Set-XrmWebResource'.
2020-02-21T13:03:04.2036425Z ##[debug]Importing cmdlet 'Set-XrmPluginAssembly'.
2020-02-21T13:03:04.2055815Z ##[debug]Importing cmdlet 'Set-XrmEntity'.
2020-02-21T13:03:04.2074774Z ##[debug]Importing cmdlet 'Set-XrmSolutionVersion'.
2020-02-21T13:03:04.2095539Z ##[debug]Importing cmdlet 'Set-XrmSolutionVersionInFolder'.
2020-02-21T13:03:04.2118322Z ##[debug]Importing cmdlet 'Split-XrmPluginAssembly'.
2020-02-21T13:03:04.2138487Z ##[debug]Importing cmdlet 'Set-XrmPluginRegistration'.
2020-02-21T13:03:04.2161112Z ##[debug]Imported CIToolkit
2020-02-21T13:03:04.2227531Z ##[debug]PS Version: 5.1.14393.3471
2020-02-21T13:03:04.2280925Z ##[debug]Microsoft.Xrm.Sdk.dll - Version : 9.0.44.892
2020-02-21T13:03:04.2304024Z ##[debug]Microsoft.Xrm.Tooling.Connector.dll - Version : 4.0.0.47
2020-02-21T13:03:04.2348743Z ##[debug]Current Security Protocol: Ssl3, Tls
2020-02-21T13:03:04.2370342Z ##[debug]Modified Security Protocol: Ssl3, Tls, Tls11, Tls12
2020-02-21T13:03:04.2451007Z ##[debug]Connecting to CRM [attempt 1]
2020-02-21T13:05:04.6945580Z ##[warning]Unable to connect to CRM: Value cannot be null.
Parameter name: identityProvider
Value cannot be null.
Parameter name: identityProviderUnable to Login to Dynamics CRM
Unable to Login to Dynamics CRM
2020-02-21T13:05:04.6954595Z ##[debug]Processed: ##vso[task.logissue type=warning]Unable to connect to CRM: Value cannot be null.%0D%0AParameter name: identityProvider%0D%0AValue cannot be null.%0D%0AParameter name: identityProviderUnable to Login to Dynamics CRM%0D%0AUnable to Login to Dynamics CRM
2020-02-21T13:05:04.6955055Z ##[warning]Unable to Login to Dynamics CRM
2020-02-21T13:05:04.6955233Z ##[debug]Processed: ##vso[task.logissue type=warning]Unable to Login to Dynamics CRM
2020-02-21T13:05:19.7020090Z ##[debug]Connecting to CRM [attempt 2]
2020-02-21T13:07:19.8735593Z ##[warning]Unable to connect to CRM: Value cannot be null.
Parameter name: identityProvider
Value cannot be null.
Parameter name: identityProviderUnable to Login to Dynamics CRM
Unable to Login to Dynamics CRM
2020-02-21T13:07:19.8736115Z ##[debug]Processed: ##vso[task.logissue type=warning]Unable to connect to CRM: Value cannot be null.%0D%0AParameter name: identityProvider%0D%0AValue cannot be null.%0D%0AParameter name: identityProviderUnable to Login to Dynamics CRM%0D%0AUnable to Login to Dynamics CRM
2020-02-21T13:07:19.8766894Z ##[warning]Unable to Login to Dynamics CRM
2020-02-21T13:07:19.8767190Z ##[debug]Processed: ##vso[task.logissue type=warning]Unable to Login to Dynamics CRM
2020-02-21T13:07:34.8845812Z ##[debug]Connecting to CRM [attempt 3]
2020-02-21T13:09:35.0594137Z ##[warning]Unable to connect to CRM: Value cannot be null.
Parameter name: identityProvider
Value cannot be null.
Parameter name: identityProviderUnable to Login to Dynamics CRM
Unable to Login to Dynamics CRM
2020-02-21T13:09:35.0594646Z ##[debug]Processed: ##vso[task.logissue type=warning]Unable to connect to CRM: Value cannot be null.%0D%0AParameter name: identityProvider%0D%0AValue cannot be null.%0D%0AParameter name: identityProviderUnable to Login to Dynamics CRM%0D%0AUnable to Login to Dynamics CRM
2020-02-21T13:09:35.0629057Z ##[warning]Unable to Login to Dynamics CRM
2020-02-21T13:09:35.0629382Z ##[debug]Processed: ##vso[task.logissue type=warning]Unable to Login to Dynamics CRM
2020-02-21T13:09:35.0723943Z ##[debug]Caught exception from task script.
2020-02-21T13:09:35.0764499Z ##[debug]Error record:
2020-02-21T13:09:35.2090058Z ##[debug]Select-WhoAmI : Couldn't connect to CRM instance after 3 attempts: Unable to connect to CRM: Value cannot be null.
2020-02-21T13:09:35.2105424Z ##[debug]Parameter name: identityProvider
2020-02-21T13:09:35.2120625Z ##[debug]Value cannot be null.
2020-02-21T13:09:35.2137200Z ##[debug]Parameter name: identityProviderUnable to Login to Dynamics CRM
2020-02-21T13:09:35.2150914Z ##[debug]Unable to Login to Dynamics CRM
2020-02-21T13:09:35.2165508Z ##[debug]At F:\BuildAgent_01\_work\tools\MSCRMBuildTools\9.1.3\xRMCIFramework\9.0.0\Ping.ps1:26 char:18
2020-02-21T13:09:35.2180233Z ##[debug]+ ... utingUser = Select-WhoAmI -ConnectionString $CrmConnectionString -Ver ...
2020-02-21T13:09:35.2193828Z ##[debug]+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-02-21T13:09:35.2208383Z ##[debug]    + CategoryInfo          : NotSpecified: (:) [Select-WhoAmI], Exception
2020-02-21T13:09:35.2223701Z ##[debug]    + FullyQualifiedErrorId : System.Exception,Xrm.Framework.CI.PowerShell.Cmdlets.SelectXrmWhoAmICommand
2020-02-21T13:09:35.2239833Z ##[debug] 
2020-02-21T13:09:35.2266399Z ##[debug]Script stack trace:
2020-02-21T13:09:35.2309665Z ##[debug]at <ScriptBlock>, F:\BuildAgent_01\_work\tools\MSCRMBuildTools\9.1.3\xRMCIFramework\9.0.0\Ping.ps1: line 26
2020-02-21T13:09:35.2324863Z ##[debug]at <ScriptBlock>, F:\BuildAgent_01\_work\_tasks\MSCRMPing_d8587a60-cd25-11e6-a324-f3fd298c325e\10.0.6\MSCRMPing.ps1: line 28
2020-02-21T13:09:35.2341231Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-02-21T13:09:35.2356794Z ##[debug]at <ScriptBlock>, <No file>: line 22
2020-02-21T13:09:35.2372560Z ##[debug]at <ScriptBlock>, <No file>: line 18
2020-02-21T13:09:35.2389265Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-02-21T13:09:35.2417130Z ##[debug]Exception:
2020-02-21T13:09:35.2467791Z ##[debug]System.Exception: Couldn't connect to CRM instance after 3 attempts: Unable to connect to CRM: Value cannot be null.
2020-02-21T13:09:35.2483701Z ##[debug]Parameter name: identityProvider
2020-02-21T13:09:35.2498230Z ##[debug]Value cannot be null.
2020-02-21T13:09:35.2513414Z ##[debug]Parameter name: identityProviderUnable to Login to Dynamics CRM
2020-02-21T13:09:35.2528798Z ##[debug]Unable to Login to Dynamics CRM
2020-02-21T13:09:35.2545669Z ##[debug]   at Xrm.Framework.CI.Common.XrmConnectionManager.ConnectToCRM(String connectionString, Int32 timeout)
2020-02-21T13:09:35.2562139Z ##[debug]   at Xrm.Framework.CI.PowerShell.Cmdlets.XrmCommandBase.BeginProcessing()
2020-02-21T13:09:35.2577392Z ##[debug]   at System.Management.Automation.Cmdlet.DoBeginProcessing()
2020-02-21T13:09:35.2599089Z ##[debug]   at System.Management.Automation.CommandProcessorBase.DoBegin()
2020-02-21T13:09:35.2657475Z ##[error]Couldn't connect to CRM instance after 3 attempts: Unable to connect to CRM: Value cannot be null.
Parameter name: identityProvider
Value cannot be null.
Parameter name: identityProviderUnable to Login to Dynamics CRM
Unable to Login to Dynamics CRM
2020-02-21T13:09:35.2657841Z ##[debug]Processed: ##vso[task.logissue type=error]Couldn't connect to CRM instance after 3 attempts: Unable to connect to CRM: Value cannot be null.%0D%0AParameter name: identityProvider%0D%0AValue cannot be null.%0D%0AParameter name: identityProviderUnable to Login to Dynamics CRM%0D%0AUnable to Login to Dynamics CRM
2020-02-21T13:09:35.2690226Z ##[debug]Processed: ##vso[task.complete result=Failed]
2020-02-21T13:09:35.3050812Z ##[section]Finishing: MSCRM CRM Ping copy

**Comment by WaelHamze** [comment]
@nishshade strange I can connect fine to crm11, have you got any special restrictions in your tenant?

**Comment by brf132** [comment]
What exactly do you have entered as the Connection String to CRM?

It took me a little bit of playing around with it to be able to connect - this is what I ended up using as ConnectionString:

AuthType=Office365;Username= user@org.onmicrosoft.com; Password=passWord;Url=https://org.crm9.dynamics.com

**Comment by nishshade** [comment]
i am using the same ConnectionString but this gives me the above error.

'AuthType=Office365;Username=xxx;Password=xxx;Url=https://gsrci.crm11.dynamics.com'

**Comment by brf132** [comment]
are you including the single quotes or not?

**Comment by nishshade** [comment]
without the quotes and with a semicolon at the end of the URL

**Comment by brf132** [comment]
Get rid of the semicolon at the end.

Use the exact format I used above, I have no semicolon at the end:

**
![image](https://user-images.githubusercontent.com/15112935/76326655-5d312980-62bf-11ea-9266-df09daf104c7.png)
**

**Comment by nishshade** [comment]
Strange!!!

It was working with the semicolon with the Hosted Microsoft Agent even earlier, basically this was the work around we were using.

Coincidentally i tried what you said and it's working with that and even if i do put a semicolon at the end of the URL. 

I would change the Release and Build pipeline to point to the Private Agent for our Nightly Build and let's see what happens. 

There was a time when this was working on and off for few days until it completely stopped working for us and so we resorted to using the Hosted Agent but i would really like to know the root cause for this.

**Comment by frick-brian** [comment]
Glad it worked!

**Comment by nishshade** [comment]
Can you help we understand why it wasn't for all these time?

**Comment by frick-brian** [comment]
I wish I could.... It's likely based on how the code-behind is constructed.

I just had to google left and right to find _exactly_ what the app expected in the Connection String. I started on the MSDN article with D365 Connection strings, and then started pulling elements out of it.  I never got it to work until I stumbled upon an article that had the connection string formatted as I have shown above.

One day, there will be better documentation available...I'm SURE of it!

**Comment by nishshade** [comment]
Yes i hope so too.

For now just rely on the luck that things might start working. Meanwhile i will try and chase Microsoft for this, let's see what they have to say.

**Comment by WaelHamze** [comment]
The connection string formats are here: https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/xrm-tooling/use-connection-strings-xrm-tooling-connect
