### ISSUE TITLE
Import Config Migration Data Failure

### ISSUE THREAD

**Issue by don-matese** [WaelHamze/dyn365-ce-vsts-tasks#198]
The Import Configuration Migration data step seems to be hanging for us.  Last night I left it running for 8hrs on ADO (local build agent thankfully) and it still seemed to hang after processing the Note entity.  I am using the configuration to migrate portal config between dev / test /uat and it has been working flawlessly until a week or so ago.

The error shown below happens then seems to hang the import process:
`2020-07-28T23:12:48.1508639Z ##[debug]Pre-Processing Entity Note--Working
2020-07-28T23:12:48.2048932Z DataMigrationUtility.Import Information: 8 : Record Count query for annotation returned 24
2020-07-28T23:12:48.2056829Z DataMigrationUtility.Import Information: 8 : Preloading PreParse Working data for Entity annotation (Note)
2020-07-28T23:12:48.3328795Z DataMigrationUtility.Import Information: 8 : Preloading PreParse Working data for Entity annotation (Note) Completed - duration: 00:00:00.1245784
2020-07-28T23:12:48.3339521Z DataMigrationUtility.Import Information: 8 : Switching Insert to Update ( Matched on Source ID ) for Note, subject = No Primary Field, Matched to ID: 851e8120-a33b-ea11-a812-000d3a0ba151
2020-07-28T23:12:48.3346840Z DataMigrationUtility.Import Verbose: 16 : Result of Check and Retrieve Record Id = 851e8120-a33b-ea11-a812-000d3a0ba151
2020-07-28T23:12:48.3355317Z DataMigrationUtility.Import Warning: 4 : Skipping Lookup record Not Available in target System: Field Name objectid requesting lookup to account ID: 07c9f066-7a3b-ea11-a812-000d3a0bad17 Name:  - All references to this record will be skipped during the import to the target system.
2020-07-28T23:12:48.3369350Z DataMigrationUtility.Import Information: 8 : Exception Raised in Begin Import
2020-07-28T23:12:48.3935558Z DataMigrationUtility.Import Error: 2 : Source	: mscorlib
2020-07-28T23:12:48.3936152Z Method	: ThrowIfExceptional
2020-07-28T23:12:48.3936319Z Date	: 29/07/2020
2020-07-28T23:12:48.3936430Z Time	: 00:12:48
2020-07-28T23:12:48.3937158Z Error	: One or more errors occurred.
2020-07-28T23:12:48.3937409Z Stack Trace	: at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
2020-07-28T23:12:48.3937743Z    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
2020-07-28T23:12:48.3938299Z    at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
2020-07-28T23:12:48.3939157Z    at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
2020-07-28T23:12:48.3939899Z    at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
2020-07-28T23:12:48.3940419Z    at Microsoft.Xrm.Tooling.Dmt.ImportProcessor.DataInteraction.ImportCrmEntityActions.ImportEntityData(entitiesEntity entity, entitiesEntity schemaEntity, ProgressItemEventArgs progressArgs)
2020-07-28T23:12:48.3941086Z    at Microsoft.Xrm.Tooling.Dmt.ImportProcessor.DataInteraction.ImportCrmEntityActions.BeginEntityImport(entitiesEntity entity)
2020-07-28T23:12:48.3941546Z ======================================================================================================================
2020-07-28T23:12:48.3941912Z Inner Exception Level 1	: 
2020-07-28T23:12:48.3942218Z Source	: Microsoft.Xrm.Tooling.Dmt.ImportProcessor
2020-07-28T23:12:48.3942417Z Method	: <CheckAndRetrieveRecordId>b__4
2020-07-28T23:12:48.3942547Z Date	: 29/07/2020
2020-07-28T23:12:48.3942659Z Time	: 00:12:48
2020-07-28T23:12:48.3943034Z Error	: Object reference not set to an instance of an object.
2020-07-28T23:12:48.3943943Z Stack Trace	: at Microsoft.Xrm.Tooling.Dmt.ImportProcessor.DataInteraction.ImportCrmEntityActions.<>c__DisplayClass99_1.<CheckAndRetrieveRecordId>b__4(KeyValuePair`2 w)
2020-07-28T23:12:48.3944425Z    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
2020-07-28T23:12:48.3944731Z    at Microsoft.Xrm.Tooling.Dmt.ImportProcessor.DataInteraction.ImportCrmEntityActions.CheckAndRetrieveRecordId(CrmServiceClient crmSvc, InsertRecordData inrecord)
2020-07-28T23:12:48.3945877Z    at Microsoft.Xrm.Tooling.Dmt.ImportProcessor.DataInteraction.ImportCrmEntityActions.<>c__DisplayClass87_0.<ImportEntityData>b__0(KeyValuePair`2 queue)
2020-07-28T23:12:48.3946266Z    at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
2020-07-28T23:12:48.3946748Z    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
2020-07-28T23:12:48.3946980Z    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
2020-07-28T23:12:48.3947268Z ======================================================================================================================
2020-07-28T23:12:48.3947667Z 
2020-07-28T23:12:48.3948066Z DataMigrationUtility.Import Information: 8 : Stage Failed
2020-07-28T23:12:48.3956279Z DataMigrationUtility.Import Information: 8 : Processing Entity: Note - Stage Failed - See log
2020-07-28T23:12:48.3965744Z Microsoft.Xrm.Tooling.ConfigurationMigration.Powershell Information: 8 : Processing Entity: Note - Stage Failed - See log--Failed
2020-07-28T23:12:48.4604933Z ##[debug]Error record:
2020-07-28T23:12:48.5149191Z ##[debug]Import-CrmDataFile : Processing Entity: Note - Stage Failed - See log
2020-07-28T23:12:48.5159886Z ##[debug]At C:\agent\BuildAndTestAgent\_work\_tool\MSCRMBuildTools\12.0.32\xRMCIFramework\9.0.0\ImportCMData.ps1:85 char:1
2020-07-28T23:12:48.5169425Z ##[debug]+ Import-CrmDataFile @importParams -EmitLogToConsole -Verbose
2020-07-28T23:12:48.5177425Z ##[debug]+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-07-28T23:12:48.5184664Z ##[debug]    + CategoryInfo          : InvalidResult: (Microsoft.Xrm.T...portCrmDataFile:ImportCrmDataFile) [Import-CrmDataFile    ], Exception
2020-07-28T23:12:48.5191760Z ##[debug]    + FullyQualifiedErrorId : 1,Microsoft.Xrm.Tooling.ConfigurationMigration.CmdLets.ImportCrmDataFile
2020-07-28T23:12:48.5198851Z ##[debug] 
2020-07-28T23:12:48.5210992Z ##[debug]Script stack trace:
2020-07-28T23:12:48.5234353Z ##[debug]at <ScriptBlock>, C:\agent\BuildAndTestAgent\_work\_tool\MSCRMBuildTools\12.0.32\xRMCIFramework\9.0.0\ImportCMData.ps1: line 85
2020-07-28T23:12:48.5242746Z ##[debug]at <ScriptBlock>, C:\agent\BuildAndTestAgent\_work\_tasks\MSCRMImportCMData_81fa890c-2b95-4d6b-bc9e-58828d754d07\12.0.4\MSCRMImportCMData.ps1: line 83
2020-07-28T23:12:48.5250510Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-07-28T23:12:48.5265628Z ##[debug]at <ScriptBlock>, <No file>: line 22
2020-07-28T23:12:48.5277385Z ##[debug]at <ScriptBlock>, <No file>: line 18
2020-07-28T23:12:48.5284411Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-07-28T23:12:48.5295620Z ##[debug]Exception:
2020-07-28T23:12:48.5324229Z ##[debug]System.Exception: Processing Entity: Note - Stage Failed - See log
2020-07-28T23:12:48.5492459Z ##[error]Processing Entity: Note - Stage Failed - See log
[tasklog_10 (1).log](https://github.com/WaelHamze/dyn365-ce-vsts-tasks/files/4993403/tasklog_10.1.log)

`

**Comment by don-matese** [comment]
This used to work perfectly for us but now fails to complete.  Any Ideas what I can do to get it working again?

**Comment by WaelHamze** [comment]
@don-matese still need help with this?

**Comment by don-matese** [comment]
No, but i will reply tomorrow with the config change i made to resolve it.

**Comment by don-matese** [comment]
Closed as it was due to the connection string.
