### ISSUE TITLE
Unable to import Canvas App solution using MSCRM Package Deployer devops task

### ISSUE THREAD

**Issue by Shrradha** [WaelHamze/dyn365-ce-vsts-tasks#69]
Hi Wael,

I am trying to deploy Canvas App solution using AZURE DevOps pipeline, When I tried to use "MSCRM Package Deployer" task  It deploy canvas app solution first time / Fresh deployment. If we try to re-deploy the  Canvas app solution it gives below error:
_Error  : CanvasApp import: FAILURE: Cannot insert duplicate key exception when executing non-query: System.Data.SqlClient.SqlCommand Exception: System.Data.SqlClient.SqlException (0x80131904): Violation of UNIQUE KEY constraint 'ndx_CanvasAppName'. Cannot insert duplicate key in object 'dbo.CanvasAppBase'. The duplicate key value is (crc48_myapp16april_de98f)._

We are successfully deploy the same canvas app package using Microsoft PackageDeployment tool. and it works every time.

**Comment by lheng18** [comment]
@WaelHamze ,  I think it must be a SDK version number issue referenced. it may have not referenced the latest SDK  which is now works on canvas app. Thanks for your help!

**Comment by WaelHamze** [comment]
@Shrradha @lheng18 I am using the latest version of all the SDK tools. Not sure though how the package deployer is relevant to this issue, all the tools does is just upload the zip file and all the processing happens on the MS backend. You can also see this is SQL error coming from the backend.

When you say you have successfully accomplished this using Microsoft Package Deployment. Are you using the UI or the PS API. I can recommend trying it using PS API as this is what the task is using.

**Comment by lheng18** [comment]
@WaelHamze We were testing it using PackageDeployment in SDK and we copied the PkgFolder folder and complied PackageDeployment dll in to the  PackageDeployment folder in SDXK. It launched an UI. How do to test it using PS API? We have a Visual Studio package deployment project from the VS extension. It generated the dll.  Thanks!

**Comment by WaelHamze** [comment]
https://docs.microsoft.com/en-us/dynamics365/customer-engagement/admin/deploy-packages-using-package-deployer-windows-powershell#use-windows-powershell-to-deploy-packages

**Comment by lheng18** [comment]
Still trying to test it from the power shell but here is the log from the build task. 
07:42.7680278Z PackageDeployer Information: 8 : ************** Solution IMPORT *****************
2019-04-18T20:07:42.7690402Z PackageDeployer Information: 8 : Starting Processing Of Solution: CanvasApp_16april01(CanvasApp_16april01), Version: 1.0.0.215, PackageVersion: 9.1
2019-04-18T20:07:43.0426903Z PackageDeployer Information: 8 : CanvasApp_16april01 : User Code Execution : OP=OverrideSolutionImportDecision : Status=Execute
2019-04-18T20:07:43.0438085Z PackageDeployer Information: 8 : CanvasApp_16april01 : User Code Execution : OP=OverrideSolutionImportDecision : Status=Complete : Duration=00:00:00.0009169
2019-04-18T20:07:43.0444134Z PackageDeployer Information: 8 : CanvasApp_16april01 - Processing Solution - Inbound version: 1.0.0.215 - Deployed Version 1.0.0.202, System Determined Import Action: Import
2019-04-18T20:07:43.0449993Z PackageDeployer Information: 8 : CanvasApp_16april01 - ImportSolution - Overwrite solution version CanvasApp_16april01 with version 1.0.0.215
2019-04-18T20:07:43.0524876Z PackageDeployer Information: 8 : CanvasApp_16april01 - Updating solution Version: 1.0.0.202 to Version : 1.0.0.215 - Importing Holding Solution - USING 7.2+ API
2019-04-18T20:07:43.0615657Z PackageDeployer Information: 8 : User Code Execution : OP=PreSolutionImport : Status=Execute
2019-04-18T20:07:43.0623152Z PackageDeployer Information: 8 : User Code Execution : OP=PreSolutionImport : Status=Complete : Duration=00:00:00.0007890
2019-04-18T20:07:43.1711208Z PackageDeployer Information: 8 : ImportSolution - Async Supported = True
2019-04-18T20:07:43.1717101Z PackageDeployer Information: 8 : DeleteAndPromote - Async Supported = True
2019-04-18T20:07:43.1723622Z PackageDeployer Information: 8 : CanvasApp_16april01 - Executing Solution Import - UploadHoldingSolutionV2
2019-04-18T20:07:51.2528886Z PackageDeployer Error: 2 : Message: CanvasApp_16april01 - Importing solution threw exception : CanvasApp import: FAILURE: Cannot insert duplicate key exception when executing non-query: System.Data.SqlClient.SqlCommand Exception: System.Data.SqlClient.SqlException (0x80131904): Violation of UNIQUE KEY constraint 'ndx_CanvasAppName'. Cannot insert duplicate key in object 'dbo.CanvasAppBase'. The duplicate key value is (crc48_myapp16april_de98f).
2019-04-18T20:07:51.2529442Z The statement has been terminated.
2019-04-18T20:07:51.2529648Z    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
2019-04-18T20:07:51.2529825Z    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
2019-04-18T20:07:51.2529981Z    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
2019-04-18T20:07:51.2530148Z    at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
2019-04-18T20:07:51.2530514Z    at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
2019-04-18T20:07:51.2530693Z    at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
2019-04-18T20:07:51.2530846Z    at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
2019-04-18T20:07:51.2531015Z    at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
2019-04-18T20:07:51.2531157Z    at Microsoft.Crm.CrmDbConnection.LockConnectionAndExecuteMethod[TResult](IDbConnection connection, Func`1 executeMethod)
2019-04-18T20:07:51.2531321Z    at Microsoft.Crm.CrmDbConnection.InternalExecuteWithRetry[TResult](Func`1 ExecuteMethod, IDbCommand command, ICrmTransaction crmTransaction)
2019-04-18T20:07:51.2531480Z    at Microsoft.Crm.CrmDbConnection.<>c__DisplayClass119_0.<InternalExecuteNonQuery>b__0()
2019-04-18T20:07:51.2531624Z    at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute[TResult](ILogger logger, EventId eventId, ActivityType activityType, Func`1 func, IEnumerable`1 additionalCustomProperties)
2019-04-18T20:07:51.2531768Z    at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute[TResult](ILogger logger, XrmTelemetryActivityType activityType, Func`1 func)
2019-04-18T20:07:51.2531930Z    at Microsoft.Crm.Platform.Server.DataEngine.SqlDataAccessManager.ExecuteNonQuery(IDbCommand command, ISqlExecutionContext context, Int32 sourceLineNumber, String memberName, String sourceFilePath)
2019-04-18T20:07:51.2532101Z    at Microsoft.Crm.BusinessEntities.BusinessProcessObject.ExecuteNonQuery(IDbCommand command, ISqlExecutionContext context)
2019-04-18T20:07:51.2532816Z    at Microsoft.Crm.Platform.SolutionAwareComponents.CreateInstanceActionBase.ExecuteCreate(IDbCommand command, ExecutionContext context)
2019-04-18T20:07:51.2532957Z ClientConnectionId:4425b35a-76da-4fda-8735-fefe80843c40
2019-04-18T20:07:51.2533088Z Error Number:2627,State:1,Class:14
2019-04-18T20:07:51.2533237Z ClientConnectionId before routing:e3e5f14c-df35-4a5d-bc15-811428c13983
2019-04-18T20:07:51.2533373Z Routing Destination:d20d3806dba8.tr223.eastus1-a.worker.database.windows.net,11058
2019-04-18T20:07:51.2533505Z Source	: mscorlib
2019-04-18T20:07:51.2533650Z Method	: HandleReturnMessage
2019-04-18T20:07:51.2533782Z Date	: 8:07:51 PM
2019-04-18T20:07:51.2533910Z Time	: 4/18/2019
2019-04-18T20:07:51.2534068Z Error	: CanvasApp import: FAILURE: Cannot insert duplicate key exception when executing non-query: System.Data.SqlClient.SqlCommand Exception: System.Data.SqlClient.SqlException (0x80131904): Violation of UNIQUE KEY constraint 'ndx_CanvasAppName'. Cannot insert duplicate key in object 'dbo.CanvasAppBase'. The duplicate key value is (crc48_myapp16april_de98f).
2019-04-18T20:07:51.2534245Z The statement has been terminated.
2019-04-18T20:07:51.2534386Z    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
2019-04-18T20:07:51.2534813Z    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
2019-04-18T20:07:51.2534981Z    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
2019-04-18T20:07:51.2535145Z    at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
2019-04-18T20:07:51.2535448Z    at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
2019-04-18T20:07:51.2535631Z    at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
2019-04-18T20:07:51.2535798Z    at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
2019-04-18T20:07:51.2535935Z    at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
2019-04-18T20:07:51.2536102Z    at Microsoft.Crm.CrmDbConnection.LockConnectionAndExecuteMethod[TResult](IDbConnection connection, Func`1 executeMethod)
2019-04-18T20:07:51.2536251Z    at Microsoft.Crm.CrmDbConnection.InternalExecuteWithRetry[TResult](Func`1 ExecuteMethod, IDbCommand command, ICrmTransaction crmTransaction)
2019-04-18T20:07:51.2536408Z    at Microsoft.Crm.CrmDbConnection.<>c__DisplayClass119_0.<InternalExecuteNonQuery>b__0()
2019-04-18T20:07:51.2536570Z    at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute[TResult](ILogger logger, EventId eventId, ActivityType activityType, Func`1 func, IEnumerable`1 additionalCustomProperties)
2019-04-18T20:07:51.2537087Z    at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute[TResult](ILogger logger, XrmTelemetryActivityType activityType, Func`1 func)
2019-04-18T20:07:51.2537249Z    at Microsoft.Crm.Platform.Server.DataEngine.SqlDataAccessManager.ExecuteNonQuery(IDbCommand command, ISqlExecutionContext context, Int32 sourceLineNumber, String memberName, String sourceFilePath)
2019-04-18T20:07:51.2537564Z    at Microsoft.Crm.BusinessEntities.BusinessProcessObject.ExecuteNonQuery(IDbCommand command, ISqlExecutionContext context)
2019-04-18T20:07:51.2537706Z    at Microsoft.Crm.Platform.SolutionAwareComponents.CreateInstanceActionBase.ExecuteCreate(IDbCommand command, ExecutionContext context)
2019-04-18T20:07:51.2537855Z ClientConnectionId:4425b35a-76da-4fda-8735-fefe80843c40
2019-04-18T20:07:51.2537985Z Error Number:2627,State:1,Class:14
2019-04-18T20:07:51.2538117Z ClientConnectionId before routing:e3e5f14c-df35-4a5d-bc15-811428c13983
2019-04-18T20:07:51.2538264Z Routing Destination:d20d3806dba8.tr223.eastus1-a.worker.database.windows.net,11058
2019-04-18T20:07:51.2538395Z Stack Trace	: Server stack trace: 
2019-04-18T20:07:51.2538530Z    at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
2019-04-18T20:07:51.2538673Z    at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
2019-04-18T20:07:51.2538849Z    at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
2019-04-18T20:07:51.2538985Z    at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)
2019-04-18T20:07:51.2539102Z 
2019-04-18T20:07:51.2539250Z Exception rethrown at [0]: 
2019-04-18T20:07:51.2539394Z    at Microsoft.Xrm.Tooling.PackageDeployment.CrmPackageCore.ImportCode.BaseImportCustomizations.ExecuteImportSolution(ConfigSolutionFile Sol, String sSolutionImportFilePath)
2019-04-18T20:07:51.2539532Z ======================================================================================================================
2019-04-18T20:07:51.2539667Z 
2019-04-18T20:07:51.2570949Z PackageDeployer Information: 8 : ****** PACKAGE DEPLOYMENT PROCESS COMPLETED. Result:FAILED  Duration:00:00:09.1018115 ******
2019-04-18T20:07:51.2586777Z PackageDeployer Information: 8 : Completed Processing Of Solution: CanvasApp_16april01(CanvasApp_16april01), Version: 1.0.0.215, PackageVersion: 9.1 , Duration: 00:00:08.4889193
2019-04-18T20:07:51.5773504Z ##[error]Failed to load solution CanvasApp_16april01, version: 1.0.0.215. See the log file.
2019-04-18T20:07:51.9201575Z ##[error]Import Failed

**Comment by lheng18** [comment]
@WaelHamze found the cause. it is Microsoft bug. They don't handle Canvas App upgrading, only support replacing yet. Thanks for looking into it.

**Comment by WaelHamze** [comment]
@lheng18 thanks for letting me know, closing issue as there is no action to be done on the task
