### ISSUE TITLE
Pack solution task fails on DevOps with Output path error "Access to the path 'D:\a\r1\a' is denied" 

### ISSUE THREAD

**Issue by spr0ut** [WaelHamze/dyn365-ce-vsts-tasks#81]
MSCRM Pack Solution Version      : 10.0.4
Solution Packager Version: 9.0.3.1
Azure DevOps Agent Job

When attempting to pack the solution, the output path parameter doesn't seem to be correctly interpreted.

The default configuration for the output path is $(build.binariesdirectory).
Pack solution fails with the following output

`Solution Packager Arguments:  /action:Pack /zipFile:"D:\a\r1\a\$(build.artifactstagingdirectory)\REDACTED.zip" /folder:"D:\a\r1\a\_CRM\REDACTED" /packageType:Unmanaged /errorlevel:Verbose /map:"D:\a\r1\a" /nologo
##[debug]Invoking SolutionPackager: D:\a\tools\MSCRMBuildTools\9.0.14\CoreTools\9.0.0\SolutionPackager.exe
Access to the path 'D:\a\r1\a' is denied.
SolutionPackager: Exception thrown: System.UnauthorizedAccessException: Access to the path 'D:\a\r1\a' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path)
   at Microsoft.Crm.Tools.SolutionPackager.Filer.Initialize(PackagerArguments arguments)
   at Microsoft.Crm.Tools.SolutionPackager.SolutionPackager..ctor(PackagerArguments arguments)
   at Microsoft.Crm.Tools.SolutionPackager.Program.Main(String[] args), returning error code '1'
CrmSvcUtil Runtime = 00:00:00.8820364
SolutionPackager exit code: 1`

It appears as though the output path is not correctly interpreting the variable.
Tested with the following settings for output path

- $(build.binariesdirectory)
- $(build.ArtifactStagingDirectory)
- D:\a\r1\a\ (shouldn't be used as it is a hard reference - but wanted to test remove variable issue)
- $(Agent.BuildDirectory)

Can you advise? The Export Solution task performs fine with the Output path set to $(Build.ArtifactStagingDirectory).

**Comment by spr0ut** [comment]
Note: Following some additional testing, the above steps are reproduceable in the release process, however attempting them as part of the build process worked.

**Comment by wunnavabk** [comment]
> Note: Following some additional testing, the above steps are reproducible in the release process, however attempting them as part of the build process worked.
From your path above D:\a\**r1**\a\  Indicates Release Process.  Technically we pack the solution during Build and then pass the Packed Solution zip file to Release pipeline.

**Comment by spr0ut** [comment]
I realise that's the usual method, however all the build/release steps should be interchangable.

**Comment by WaelHamze** [comment]
$(build.binariesdirectory) is the default value as in most cases the task is used during builds.

However you have the flexibility to change it to whatever folder you like during builds/releases as long as the folder exists and the agent has access to that folder.
