### ISSUE TITLE
Backup - Unable to deserialize the response

### ISSUE THREAD

**Issue by pepijng** [WaelHamze/dyn365-ce-vsts-tasks#84]
We have used the Dynamics Backup feature in one of our release pipelines. For a couple of months it suddenly stopped working resulting in a "Unable to deserialize the response." error.

The issue occurs on both local and hosted agents.

**Comment by rfontijn** [comment]
Same issue here. Tried to use Backup task but got the same error.

`Entering OnlineInstanceFunctions.ps1
2019-06-18T09:38:04.7644901Z ##[debug]Leaving OnlineInstanceFunctions.ps1
2019-06-18T09:38:04.7713813Z ##[debug]Connecting to API server: https://admin.services.crm4.dynamics.com/
2019-06-18T09:38:04.7902592Z ##[debug]Entering GetCrmInstances - ProcessRecord
2019-06-18T09:38:04.7928120Z ##[debug]Executing GetCrmInstances
2019-06-18T09:38:04.8172613Z ##[debug]Requesting Authentication - Start
2019-06-18T09:38:04.8212078Z ##[debug]Requesting Authority From server - Start
2019-06-18T09:38:04.9881436Z ##[debug]Requesting Authority From server - Finished : 00:00:00.1665584
2019-06-18T09:38:05.4775274Z ##[debug]Requesting Authentication - Completed : 00:00:00.6596592
2019-06-18T09:38:10.1111167Z ##[debug]Failed GetCrmInstances - ProcessRecord : 00:00:05.3186372
2019-06-18T09:38:10.1414816Z ##[debug]Message: Unable to deserialize the response. => Error converting value "Default" to type 'Microsoft.Xrm.Services.Admin.Client.Models.InstanceType'. Path '[2].Type', line 72, position 22. => Requested value 'Default' was not found.
2019-06-18T09:38:10.1446568Z ##[debug]Source	: Xrm.Online.Admin.Client
2019-06-18T09:38:10.1464401Z ##[debug]Method	: MoveNext
2019-06-18T09:38:10.1479223Z ##[debug]Date	: 18-6-2019
2019-06-18T09:38:10.1490641Z ##[debug]Time	: 11:38:10
2019-06-18T09:38:10.1505733Z ##[debug]Error	: Unable to deserialize the response.
2019-06-18T09:38:10.1517070Z ##[debug]Stack Trace	: at Microsoft.Xrm.Services.Admin.Client.D365CEAdminClient.<GetInstancesWithHttpMessagesAsync>d__30.MoveNext()
2019-06-18T09:38:10.1527386Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2019-06-18T09:38:10.1540415Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-06-18T09:38:10.1551113Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-06-18T09:38:10.1561985Z ##[debug]   at Microsoft.Xrm.Services.Admin.Client.D365CEAdminClientExtensions.<GetInstancesAsync>d__9.MoveNext()
2019-06-18T09:38:10.1573963Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2019-06-18T09:38:10.1591126Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-06-18T09:38:10.1604411Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-06-18T09:38:10.1615496Z ##[debug]   at Microsoft.Xrm.Services.Admin.Client.D365CEAdminClientExtensions.GetInstances(ID365CEAdminClient operations)
2019-06-18T09:38:10.1625614Z ##[debug]   at Microsoft.Xrm.OnlineManagementAPI.GetCrmInstances.ProcessRecord()
2019-06-18T09:38:10.1635398Z ##[debug]======================================================================================================================`

**Comment by rfontijn** [comment]
I think the Instance type "Default" is not known by the enum.
In my environment I see one of that type that is causing the trouble I think...

Type Total Consumed
      ---- ----- --------
Production    43        2
   Sandbox     7       48
   Support     0        2
   Preview     0        0
     Trial     0       16
   Default     0        1
 Developer     0        4

**Comment by WaelHamze** [comment]
@pepijng @rfontijn I use this task on daily basis and not faced this issue, are you trying to use it on an instance of type default?

I have updated to the latest SDK, can you give this another try?

**Comment by pepijng** [comment]
And it’s working again!

**Comment by rfontijn** [comment]
You did a great job, working again!

It was looping through all the instances to find the instance by name, so if one of them was 'Default', it failed.
